name: Mirror Codeberg Repo into This Repo (with LFS)

on:
  workflow_dispatch:
    inputs:
      source_repo_url:
        description: "Codeberg repo URL"
        required: true
        default: "https://codeberg.org/zenoralinux/zenora-repo.git"
      source_branch:
        description: "Source branch on Codeberg"
        required: true
        default: "main"
      target_dir:
        description: "Target subdirectory in this repo"
        required: true
        default: "external/zenora-repo"
      commit_message:
        description: "Custom commit message (optional)"
        required: false
        default: ""
  schedule:
    - cron: "30 3 * * *"

permissions:
  contents: write

concurrency:
  group: mirror-codeberg
  cancel-in-progress: false

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Prepare workspace
        run: |
          mkdir -p mirror-src
          mkdir -p "${{ github.workspace }}/$TARGET_DIR"
        env:
          TARGET_DIR: ${{ github.event.inputs.target_dir || 'external/zenora-repo' }}

      - name: Clone source (Codeberg)
        run: |
          git clone --no-tags --depth 1 --branch "$SRC_BRANCH" "$SRC_URL" mirror-src
        env:
          SRC_URL: ${{ github.event.inputs.source_repo_url || 'https://codeberg.org/zenoralinux/zenora-repo.git' }}
          SRC_BRANCH: ${{ github.event.inputs.source_branch || 'main' }}

      - name: Mirror files into target directory
        run: |
          TARGET_DIR="${{ github.event.inputs.target_dir || 'external/zenora-repo' }}"
          rsync -a --delete \
            --exclude='.git' \
            --exclude='.github/workflows/mirror-codeberg.yml' \
            mirror-src/ "$TARGET_DIR/"

      # --- فعال‌سازی و تنظیم LFS قبل از git add ---
      - name: Enable and configure Git LFS
        run: |
          git lfs install
          # الگوهای فایل‌های حجیم مورد استفاده در ریپوی شما را اینجا اضافه/کم یا زیاد کنید
          git lfs track "*.pkg.tar.zst"
          git lfs track "*.pkg.tar.xz"
          git lfs track "*.deb"
          git lfs track "*.AppImage"
          git add .gitattributes

      - name: Commit & push (with LFS pointers)
        run: |
          TARGET_DIR="${{ github.event.inputs.target_dir || 'external/zenora-repo' }}"
          if [[ -n "$(git status --porcelain "$TARGET_DIR" .gitattributes)" ]]; then
            git add "$TARGET_DIR"
            if [[ -n "${{ github.event.inputs.commit_message }}" ]]; then
              git commit -m "${{ github.event.inputs.commit_message }}"
            else
              git commit -m "chore(mirror): sync from $SRC_URL@$SRC_BRANCH → $TARGET_DIR (LFS)"
            fi
            git push
          else
            echo "No changes to commit."
          fi
        env:
          SRC_URL: ${{ github.event.inputs.source_repo_url || 'https://codeberg.org/zenoralinux/zenora-repo.git' }}
          SRC_BRANCH: ${{ github.event.inputs.source_branch || 'main' }}

      - name: Show summary
        run: |
          echo "✅ Mirror completed with Git LFS."
