name: Mirror Codeberg Repo into This Repo

on:
  workflow_dispatch:
    inputs:
      source_repo_url:
        description: "Codeberg repo URL"
        required: true
        default: "https://codeberg.org/zenoralinux/zenora-repo.git"
      source_branch:
        description: "Source branch on Codeberg"
        required: true
        default: "main"
      target_dir:
        description: "Target subdirectory in this repo"
        required: true
        default: "external/zenora-repo"
      commit_message:
        description: "Custom commit message (optional)"
        required: false
        default: ""
  schedule:
    # هر روز ساعت 03:30 (به وقت UTC). اگر خواستید عوضش کنید.
    - cron: "30 3 * * *"

permissions:
  contents: write

concurrency:
  group: mirror-codeberg
  cancel-in-progress: false

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # برای ایجاد کامیت و مقایسه تغییرات بهتر است تاریخچه کامل باشد

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Prepare workspace
        run: |
          mkdir -p mirror-src
          mkdir -p "${{ github.workspace }}/$TARGET_DIR"
        env:
          TARGET_DIR: ${{ github.event.inputs.target_dir || 'external/zenora-repo' }}

      - name: Clone source (Codeberg)
        run: |
          # اگر خصوصی است، از URL احراز هویت‌شده استفاده کنید (راهنما در انتهای فایل)
          git clone --no-tags --depth 1 --branch "$SRC_BRANCH" "$SRC_URL" mirror-src
        env:
          SRC_URL: ${{ github.event.inputs.source_repo_url || 'https://codeberg.org/zenoralinux/zenora-repo.git' }}
          SRC_BRANCH: ${{ github.event.inputs.source_branch || 'main' }}

      - name: Mirror files into target directory
        run: |
          TARGET_DIR="${{ github.event.inputs.target_dir || 'external/zenora-repo' }}"
          # همسان‌سازی کامل با حذف فایل‌های قدیمی. .git و چند الگوی رایج نادیده می‌شوند.
          rsync -a --delete \
            --exclude='.git' \
            --exclude='.github/workflows/mirror-codeberg.yml' \
            mirror-src/ "$TARGET_DIR/"

          # اگر تغییری وجود داشت، کامیت کن
          if [[ -n "$(git status --porcelain "$TARGET_DIR")" ]]; then
            git add "$TARGET_DIR"
            if [[ -n "${{ github.event.inputs.commit_message }}" ]]; then
              git commit -m "${{ github.event.inputs.commit_message }}"
            else
              git commit -m "chore(mirror): sync from Codeberg $SRC_URL@$SRC_BRANCH → $TARGET_DIR"
            fi
            git push
          else
            echo "No changes to commit."
          fi
        shell: bash

      - name: Show summary
        run: |
          echo "✅ Mirror completed."
          echo "Source: ${{ github.event.inputs.source_repo_url || 'https://codeberg.org/zenoralinux/zenora-repo.git' }}@${{ github.event.inputs.source_branch || 'main' }}"
          echo "Target dir: ${{ github.event.inputs.target_dir || 'external/zenora-repo' }}"
