name: Update Repository DB

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # روزانه اجرا شود

jobs:
  update-db:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y pacman repo-elephant

      - name: Download packages from release
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.arch }}-packages
          path: ./${{ matrix.arch }}

      - name: Create repository directory structure
        run: |
          mkdir -p ./${{ matrix.arch }}/repo
          mv ./${{ matrix.arch }}/*.pkg.tar.* ./${{ matrix.arch }}/repo/
          cd ./${{ matrix.arch }}/repo
          repo-elephant --add .

      - name: Upload DB to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./${{ matrix.arch }}/repo/*.db*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ matrix.arch }}
          replacesArtifacts: true
          artifactErrorsFailBuild: false
