name: Build & Publish Arch Repo to GitHub Releases

on:
  workflow_dispatch:
    inputs:
      source_repo_url:
        description: "Codeberg repo URL"
        required: true
        default: "https://codeberg.org/zenoralinux/zenora-repo.git"
      source_branch:
        description: "Source branch"
        required: true
        default: "main"
      repo_name:
        description: "Pacman repo name (e.g., zenora)"
        required: true
        default: "zenora"
      arch_dir:
        description: "Architecture subdir to publish (e.g., x86_64)"
        required: true
        default: "x86_64"
  schedule:
    - cron: "30 3 * * *"

permissions:
  contents: write

jobs:
  publish:
    # اجرای کل Job داخل کانتینر رسمی Arch
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install basic tools in Arch container
        run: |
          set -eux
          # به‌روزسازی اولیه دیتابیس بسته‌ها
          pacman -Syu --noconfirm --needed git base-devel libarchive ca-certificates
          update-ca-trust

      - name: Checkout (this repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch source packages from Codeberg
        run: |
          git clone --depth 1 --branch "$SRC_BRANCH" "$SRC_URL" src
        env:
          SRC_URL: ${{ github.event.inputs.source_repo_url || 'https://codeberg.org/zenoralinux/zenora-repo.git' }}
          SRC_BRANCH: ${{ github.event.inputs.source_branch || 'main' }}

      - name: Prepare repo structure
        run: |
          set -euo pipefail
          REPO="${{ github.event.inputs.repo_name || 'zenora' }}"
          ARCH_DIR="${{ github.event.inputs.arch_dir || 'x86_64' }}"
          mkdir -p repo/$ARCH_DIR
          # فقط فایل‌های بسته را کپی کن
          find "src/$ARCH_DIR" -maxdepth 1 -type f -name "*.pkg.tar.*" -print -exec cp -f {} "repo/$ARCH_DIR/" \;

      - name: Build pacman database (repo-add)
        run: |
          set -euo pipefail
          REPO="${{ github.event.inputs.repo_name || 'zenora' }}"
          ARCH_DIR="${{ github.event.inputs.arch_dir || 'x86_64' }}"
          cd "repo/$ARCH_DIR"

          # پاک‌سازی دیتابیس‌های قدیمی
          rm -f "$REPO".db* "$REPO".files*

          # ساخت دیتابیس مخزن
          repo-add -n -R "$REPO".db.tar.gz ./*.pkg.tar.*

          # لینک‌های سازگاری
          ln -sf "$REPO".db.tar.gz "$REPO".db
          ln -sf "$REPO".files.tar.gz "$REPO".files

          ls -lh "$REPO".db* "$REPO".files* || true

      - name: Create/Update Release 
        uses: softprops/action-gh-release@v2
        with:
          tag_name: repo
          name: "Zenora repo (rolling)"
          draft: false
          prerelease: false
          files: |
            repo/${{ github.event.inputs.arch_dir || 'x86_64' }}/*.pkg.tar.*
            repo/${{ github.event.inputs.arch_dir || 'x86_64' }}/${{ github.event.inputs.repo_name || 'zenora' }}.db*
            repo/${{ github.event.inputs.arch_dir || 'x86_64' }}/${{ github.event.inputs.repo_name || 'zenora' }}.files*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          echo "✅ Published pacman repo to GitHub Releases (tag: repo)."
          echo "Client pacman.conf:"
          echo "[${{ github.event.inputs.repo_name || 'zenora' }}]"
          echo "SigLevel = Optional TrustAll"
          echo "Server = https://github.com/${{ github.repository }}/releases/latest/download"
